spring:
  application:
    name: service-flight-system

  datasource:
    url: ${DB_URL}
    username: system_user
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public

  config:
    import: optional:consul:/

  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        health-check-path: /health
        service-name: ${spring.application.name}
        hostname: ${HOSTNAME}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"

# CORS configuration
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

logging:
  level:
    org:
      springframework:
        dao: DEBUG

